"""
WHY ARE THESE TESTS HERE?
API = the point of contact with the user (Streamlit, mobile app, hospital system).
If the /analyze endpoint breaks → the user cannot get results.
If /login returns a 500 error → nobody can log in to the system.

These tests verify that the API works correctly from the OUTSIDE.
They do not concern themselves with internal models, databases, etc. — only:
"When I send this data to this URL, does it return the correct format?"


HTTP STATUS CODES:
200 = Success
400 = Bad request (missing parameters, etc.)
401 = Unauthorised (no token or incorrect token)
403 = Forbidden (token present but no authorisation)
422 = Invalid data format
500 = Server error (there is a bug in our code)
"""


import  pytest 
import os
import sys

sys.path.append(os.getcwd)
from configs.config import cfg

def api_is_running():
    """
    Check if the API is working.
    http://127.0.0.1:8000/docs → The Swagger page automatically generated by FastAPI.
    If we can access this page, it means the API is working.
    try/except → Returns False if a connection error occurs (API is down).
    timeout=2 → Wait for 2 seconds; if no response is received, give up.
    """

    try:
        import requests
        r= requests.get("http://127.0.0.1:8000/docs", timeout=2)
        return r.status_code == 200
    
    except Exception:
        return False
    

"""
 pytestmark → applies to ALL tests in this file
 skipif → skip tests if the condition is True
 In other words: if the API isn’t working, none of the tests in this file will run
"""
pytestmark = pytest.mark.skipif(
    not api_is_running(),
    reason="API is not running.Start it first: uvicor src.api.main:app"
)

class TestAuthEndpoints:
    """
    Tests authentication endpoints.

    Flow:
    1. Register → create a new account
    2. Login → submit email and password → receive a JWT token
    3. Access protected endpoints using the token (e.g. analyse)

    What is a JWT token?
    JSON Web Token — an encrypted string.
    It contains user information and an expiry date.
    It is sent in the header with every request:
    Authorization: Bearer eyJhbGciOiJIUzI1NiIs...
    """

    BASE_URL = "http://127.0.0.1:8000"
    TEST_EMAIL = "test_ci@dermascan.com"
    TEST_PASSWORD = "test123456"
    TEST_NAME = "CI Test User"

    def test_Register(self):
        """
        Can new users sign up?
        200 = successful registration
        400 = user already exists
        """
        import requests
        r= requests.post(f"{self.BASE_URL}/users/register", json={
            "email": self.TEST_EMAIL,
            "password": self.TEST_PASSWORD,
            "full_name": self.TEST_NAME
        })

        assert r.status_code in [200,400]

    def test_login(self):
        """
        Can registered users log in?

        If the login is successful, the response should contain an "access_token".
        We will use this token in other endpoints.
        """

        import requests
        requests.post(f" {self.BASE_URL}/users/register",json = {
            "email": self.TEST_EMAIL,
            "password": self.TEST_PASSWORD,
            "full_name": self.TEST_NAME
        })

        r = requests.post(f"{self.BASE_URL}/users/login", json={
            "email": self.TEST_EMAIL,
            "password": self.TEST_PASSWORD
        })

        assert r.status_code == 200
        
        data = r.json()
        assert "access_token" in data

    def test_login_wrong_password(self):
        """
        Login attempts with an incorrect password should be rejected.

        Security test — it should not be possible to log in with an incorrect password.
        We expect a 401 (Unauthorised) or 400 (Bad Request) response.
        If a 200 response is returned → SECURITY VULNERABILITY!
        """
        import requests
        r= requests.post(f"{self.BASE_URL}/users/login", json= {
            "email": self.TEST_EMAIL,
            "password": "wrongpassword"
        })

        assert r.status_code in [401,400]


    def analyze_without_token(self):
        """
        The analyse endpoint must not be accessible without a token.

        Protected endpoints require a JWT token.
        Requests made without a token should be rejected.

        401 = Unauthorised (no token)
        403 = Forbidden (token present but unauthorised)
        422 = Unprocessable Entity (missing form fields)

        """
        import requests
        r = requests.post(f"{self.BASE_URL}/analyze")
        assert r.status_code in [401, 403 , 422]


class TestAnalyzeEndpoint:
    """
    Tests the 'Analyze' endpoint.

    This endpoint is one of the most important parts of the project:
    1. Retrieves an image
    2. Crops it using YOLO
    3. Classifies it using EfficientNet
    4. Performs metadata fusion using XGBoost
    5. Applies a threshold
    6. Returns the result as JSON

    This test verifies that the OUTPUT of this entire chain is in the correct format.
    """
    BASE_URL = "http://127.0.0.1:8000"
    TEST_EMAIL = "test_ci@dermascan.com"
    TEST_PASSWORD = "test123456"

    def _get_token(self):
        """
        Obtain a JWT token for the test user.

        Each test function must run independently — which is why we
        re-obtain the token in every test. (This will work even if the previous test fails)

        Starts with "_" → pytest does not recognise this as a test.
        """

        import requests

        requests.post(f" {self.BASE_URL}/users/register", json={
            "email": self.TEST_EMAIL,
            "password": self.TEST_PASSWORD,
            "full_name": "CI Test User"
        })
        r = requests.post(f"{self.BASE_URL}/users/login", json={
            "email": self.TEST_EMAIL,
            "password": self.TEST_PASSWORD
        })
        return r.json()["access_token"]

    def test_analyze_returns_correct_format(self):
        """
        Does the `analyze` endpoint return the correct JSON format?

        STEPS:
        1. Obtain a token (log in)
        2. Create a dummy 300x300 JPEG image
        3. Send a POST request to `/analyze` (in multipart/form-data format)
        4. Check that the response contains the correct fields

        WHY A FAKE IMAGE?
        We are not using a real dermoscope image because:
        - The test needs to be quick (no need to read files, etc.)
        - We are not testing whether the result is CORRECT (this is not a model accuracy test)
        - We are only testing whether the FORMAT is correct

        WHAT IS MULTIPART/FORM-DATA?
        An HTTP format used for file uploads.
        files={...} → sends a file
        data={...} → sends form fields
        headers={...} → sends a JWT token
        """
        import requests
        import numpy as np
        from PIL import Image
        import io

        token = self._get_token()
        img = Image.fromarray(
            np.random.randint(0, 255, (300, 300, 3),dtype=np.uint8)
        )

        buf = io.BytesIO()
        img.save(buf, format= "JPEG")
        buf.seek(0)

        r = requests.post(
            f"{self.BASE_URL}/analyze",
            files={"file": ("test.jpg", buf, "image/jpeg")}, 
            data={                                               
                "age": "45",
                "sex": "male",
                "anatom_site": "upper extremity",
                "needs_heatmap": "false",
                "full_name": "Test Patient"
            },
            headers={"Authorization": f"Bearer {token}"}  
        )
        assert r.status_code == 200
        data = r.json()

        
        assert "prediction" in data     
        assert "diagnosis" in data      
        assert "confidence" in data    
        assert "all_probabilities" in data  
        assert "debug" in data          

        
        assert data["prediction"] in ["Risky", "Benign"]
        assert 0 <= data["confidence"] <= 1
        assert len(data["all_probabilities"]) == cfg.NUM_CLASSES

    def test_analyze_with_heatmap(self):
        """
        Does it return a Base64 string when a heatmap is requested?

        When `needs_heatmap=true` is sent, the `heatmap_base64` field in the response
        should contain a non-empty Base64 string.

        What is Base64?
        An encoding that converts binary data (image bytes) into ASCII text.
        This allows images to be sent within JSON.
        Streamlit decodes this string and displays it as an image.
        """

        import requests
        import numpy as np
        from PIL import Image
        import io

        token = self._get_token()

        img = Image.fromarray(
            np.random.randint(0, 255, (300, 300, 3), dtype=np.uint8)
        )

        buf = io.BytesIO()
        img.save(buf, format = "JPEG")
        buf.seek(0)

        r = requests.post(
            f"{self.BASE_URL}/analyze",
            files={"file": ("test.jpg", buf, "image/jpeg")},
            data={
                "age": "45",
                "sex": "male",
                "anatom_site": "upper extremity",
                "needs_heatmap": "true",          # ← heatmap istiyoruz
                "full_name": "Test Patient Heatmap"
            },
            headers={"Authorization": f"Bearer {token}"}
        )

        assert r.status_code == 200
        data = r.json()
        assert "heatmap_base64" in data
        assert len(data["heatmap_base64"]) > 0, "Heatmap should not be empty"


