services:
  db:
    image: postgres:16
    ports:
      - "5444:5432"
    container_name: derma_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dermascan
   
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - derma_network

  api:
    build: .
    container_name: derma_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/dermascan
      SECRET_KEY: ${SECRET_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    depends_on:
      - db
    restart: always
    networks:
      - derma_network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: derma_ui  
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000   
    depends_on:
      - api
    restart: always
    networks:
      - derma_network

  nginx:
    image: nginx:alpine
    container_name: derma_nginx
    ports:
      - "80:80"    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - ui
    restart: always
    networks:
      - derma_network

volumes:
  postgres_data:
  
networks:
  derma_network:
    driver: bridge