meta:
  oof_csv_path: "data/derm12345/derm12345_metadata_train.csv"
  oof_image_dir: "data/derm12345/train"
  oof_image_col: "image"
  oof_label_col: "label"
  oof_group_col: "patient_id"
  oof_strip_suffix: "_downsampled"
  oof_model_path: "experiments/models/vision/midas_model.ckpt"
  oof_output_path: "data/processed/oof_derm12345meta_dataset.csv"

  meta_csv_path: "data/processed/oof_derm12345meta_dataset.csv"
  meta_model_dir: "models/xgb_metalearner"
  meta_model_path: "models/xgb_metalearner/xgb_meta_learner.json"
  meta_feature_path: "models/xgb_metalearner/xgb_features.pkl"
  meta_folds: 5
  cnn_features:
    - "0_mel"
    - "1_nv"
    - "2_bcc"
    - "3_ak"
    - "4_bkl"
    - "5_df"
    - "6_vasc"
    - "7_scc"

  xgb_params:
    objective: 'multi:softprob'
    num_class: 8
    eval_metric: 'mlogloss'
    max_depth: 4
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    n_estimators: 150